site_name: "Router Test Kit"
theme:
  name: material
  color_mode: auto

repo_url: https://github.com/alex-anast/router-test-kit

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
